# Generated by Django 3.0.5 on 2020-04-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='address',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='tguser',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
