# Generated by Django 3.0.5 on 2020-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200420_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
