# Generated by Django 3.0.5 on 2020-04-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
