# Generated by Django 3.0.5 on 2020-04-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tguser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearBarber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, null=True)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Barber')),
            ],
        ),
    ]
