# Generated by Django 3.0.5 on 2020-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tguser_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbarber',
            name='sort_by_leng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
